# from chatterbot import ChatBot
# from chatterbot.trainers import ListTrainer
# import logging
# logger = logging.getLogger()
# logger.setLevel(logging.CRITICAL)
# bot = ChatBot('Bot')
# trainer = ListTrainer(bot)
# https://cloudcounselage.co.in/faq
# files = ['intents.txt']
keywords = {1: {1: ['access', 'Bitrix24', 'account']},
            2: {1: ['job profile'],
                2: ['only', 'tech']},
            3: {1: ['workgroups', 'part'],
                2: ['workgroups', 'in']},
            4: {1: ['error', 'User Not Found'],
                2: ['error', 'user not found'],
                3: ['Website Redirection Issue', 'Token', 'not working'],
                4: ['website redirection issue', 'Token', 'not working']},
            5: {1: ['login', 'training'],
                2: ['Login', 'training'],
                3: ['register', 'again', 'access']},
            6: {1: ['invalid user', 'token'],
                2: ['not working']},
            7: {1: ['instructions', 'video'],
                2: ['instructions', 'tutorial'],
                3: ['steps', 'video'],
                4: ['steps', 'tutorial']},
            8: {1: ['pass', 'training'],
                2: ['pass', 'training', 'certificate']},
            9: {1: ['see', 'task']},
            10: {1: ['report']},
            11: {1: ['time', 'token']},
            12: {1: ['just' 'joined'],
                 2: ['start', 'internship']},
            13: {1: ['complet']},
            14: {1: ['time']},
            15: {1: ['options', 'continue'],
                 2: ['next', 'step']},
            16: {1: ['result']},
            17: {1: ['quiz']},
            18: {1: ['after', 'complet']},
            19: {1: ['Browser'],
                 2: ['browser']},
            20: {1: ['step', 'complet', '14'],
                 2: ['step', 'complet', '2']},
            21: {1: ['resume', 'finish']},
            22: {1: ['mobile']},
            23: {1: ['chose', 'both'],
                 2: ['opted', 'both'],
                 3: ['internship', 'also']},
            24: {1: ['switch'],
                 2: ['change']},
            25: {1: ['progress']},
            26: {1: ['page', 'login'],
                 2: ['page', 'logged']},
            27: {1: ['find', 'workgroup'],
                 2: ['visible', 'workgroup'],
                 3: ['see', 'workgroup']},
            28: {1: ['token', 'redirect', 'page']},
            29: {1: ['deadline'],
                 2: ['dates']},
            30: {1: ['LP2'],
                 2: ['lp2']},
            31: {1: ['LP3'],
                 2: ['lp3']},
            32: {1: ['after', 'LP3'],
                 2: ['after', 'lp3'],
                 3: ['lp3', 'next'],
                 4: ['LP3', 'next']},
            33: {1: ['skip']},
            34: {1: ['clock']},
            35: {1: ['skip', 'Resource', 'link'],
                 2: ['skip', 'resource', 'link']},
            36: {1: ['exam'],
                 2: ['Exam']},
            37: {1: ['college']},
            38: {1: ['other', 'internship']},
            39: {1: ['offer'],
                 2: ['stipend'],
                 3: ['Live', 'Project'],
                 4: ['live', 'project']},
            40: {1: ['join', 'letter']},
            41: {1: ['letter', 'complet']},
            42: {1: ['project']},
            43: {1: ['workgroup', 'task'],
                 2: ['workgroup', 'training']},
            44: {1: ['submit'],
                 2: ['group', 'project'],
                 3: ['group', 'assignment'],
                 4: ['individual']},
            45: {1: ['week']},
            46: {1: ['lp1', 'necessary'],
                 2: ['LP1', 'necessary']},
            47: {1: ['lp2', 'training'],
                 2: ['LP2', 'training'],
                 3: ['lp2', 'course'],
                 4: ['LP2', 'course']},
            48: {1: ['site', 'do'],
                 2: ['resource', 'do']},
            49: {1: ['certificat']},
            50: {1: ['load', 'time']},
            51: {1: ['lp', 'live', 'project'],
                 2: ['LP', 'live', 'project'],
                 3: ['lp', 'Live', 'Project'],
                 4: ['LP', 'Live', 'Project']},
            52: {1: ['enough', 'complet']},
            53: {1:  ['quiz', 'access']},
            54: {1: ['receive', 'Bitrix24', 'account'],
                 2: ['get', 'Bitrix24', 'account']},
            55: {1: ['friend', 'apply'],
                 2: ['awareness'],
                 3: ['representative']},
            56: {1: ['induction'],
                 2: ['Induction']},
            57: {1: ['social', 'media']},
            58: {1: ['efficiency'],
                 2: ['Efficiency']},
            59: {1: ['mentorship'],
                 2: ['Mentorship'],
                 3: ['doubt']},
            60: {1: ['statement', 'project'],
                 2: ['statement', 'Project']},
            61: {1: ['hire'],
                 2: ['part', 'team']},
            62: {1: ['office']},
            63: {1: ['extend']},
            64: {1: ['certificat', 'technolog', 'add']},
            65: {1: ['live', 'project', 'technolog'],
                 2: ['Live', 'Project', 'technolog']},
            66: {1: ['clock', 'affect']},
            67: {1: ['LP3', 'Live', 'Project'],
                 2: ['LP3', 'live', 'project'],
                 3: ['lp3', 'Live', 'Project'],
                 4: ['lp3', 'live', 'project']},
            68: {1: ['add', 'tech']},
            69: {1: ['polic', 'intern']},
            70: {1: ['acknowledge', 'report'],
                 2: ['repl', 'report']},
            71: {1: ['exclamation'],
                 2: ['remaining']},
            72: {1: ['induction'],
                 2: ['intro']},
            73: {1: ['induction', 'attend']},
            74: {1: ['noname'],
                 2: ['file'],
                 3: ['attachment']},
            75: {1: ['code', 'LP3'],
                 2: ['code', 'lp3'],
                 3: ['assignment'],
                 4: ['Assignment']},
            76: {1: ['lp3', 'submi'],
                 2: ['LP3', 'submi']},
            77: {1: ['social', 'media']},
            78: {1: ['case', 'project'],
                 2: ['case', 'Project']},
            79: {1: ['clock', 'done'],
                 2: ['clock', 'complet']},
            80: {1: ['after', '1'],
                 2: ['after', 'one']},
            81: {1: ['issue', 'help'],
                 2: ['problem', 'help']},
            82: {1: ['friend']},
            83: {1: ['query', 'LP3'],
                 2: ['query', 'lp3'],
                 3: ['doubt', 'lp3'],
                 4: ['doubt', 'LP3']},
            84: {1: ['appoint', 'letter'],
                 2: ['Appoint', 'Letter']},
            85: {1: ['download', 'lp3'],
                 2: ['download', 'LP3'],
                 3: ['view', 'lp3'],
                 4: ['view', 'LP3']},
            86: {1: ['cloud', 'computing'],
                 2: ['Cloud', 'Computing']},
            87: {1: ['error', 'SQLSTATE']},
            88: {1: ['thank'],
                 2: ['Thank']},
            89: {1: ['hi'],
                 2: ['Hi'],
                 3: ['Hello'],
                 4: ['hello']}
            }
responses = {0: "Sorry, can you repeat again.",
             1: "Go to https://cloudcounselage24.bitrix24.com/.\n\t On the Login page, in the, ‘Enter the phone number or email’, type in your email id that you have registered with Cloud Counselage and Click ‘Forgot Password’.\n\t In case the problem persists, please write a mail to hrsupport@cloudcounselage.in",
             2: "Your job profile is 'Technology - Intern'; if you're in cloud computing technology to update in your LinkedIn or resume, you can write as 'Cloud Computing - Intern'.\n\t Yes, you'll only work in the technology you're selected for but you can take the training of other technologies.",
             3: "Every intern should be a part of 2 workgroups.\n\t 1. Group 202003-IP = This is a general workgroup. Everyone who is enrolled in IP should be a part of this workgroup.\n\t 2. Group 202003-IP-Technology = This is a technology-specific workgroup. You'll be added to the technology you had enrolled for.\n\t For example Group 202003-IP-Python for students who enrolled for python.\n\t If anyone has not been added to any of these workgroups, kindly message Cloud Counselage HR regarding the same over bitrix24 platform.",
             4: "Please watch the videos shared with the invite and you should not face any problems in accessing the training. Please follow the protocol shown in the videos.",
             5: "Yes, you need to register for every module of training. Some of you are facing login issues, we have kept the training visible without login.\n\t Even then, to post a comment and give a quiz you'll have to login.\n\t In case you face difficulty to do so, please try to perform your quiz or post a comment by using a different browser or incognito mode.",
             6: "For each training of LP1, there are different tokens. Please read the tasks or watch the videos again meticulously. Try accessing it in incognito mode.",
             7: "Ensure you're using the right token",
             8: "No, but please ensure you complete the training.",
             9: "Please remove the default 'In Progress' from your filter of the task section and try.",
             10: "As mentioned in the video, please write what you have done this week and request approval from your supervisor by clicking on 'send to supervisor'.",
             11: "We understand that it sometimes becomes tedious to access the training and we highly appreciate your support in making the training possible.\n\t We only do this for security reasons and we're trying to find a way to minimise the token use.\n\t For now, please note that in LP1 there are 3 types tokens:\n\t 1. One for each technology, you're a part of.\n\t 2. The lp1 home page.\n\t 3. The 6 tokens (one for each step)",
             12: "Please go through the mail from which you have accepted the invite and check the task section as well.",
             13: "There are tokens for each training in the task, if this learning path is done, please wait for the next learning path to begin and then please try to finish it.\n\t If you are done with LP3 please wait for Live Projects to begin.",
             14: "There are codes in the LP1 assignment, and each time you have to register also, please check your task description.",
             15: "Go back to the technology Page. Enter the respective tokens and then work. follow the same process every time.",
             16: "They are just for your practice and not for our record, so you don't need the results of LP1 and LP2 training.",
             17: "Please retry after some time in an incognito window",
             18: "Mark your task as finished and wait for the next instructions.",
             19: "Google Chrome is recommended.",
             20: "It's preferred if you complete the LP1 training in 2 weeks but not mandatory.\n\t LP1, LP2, and LP3 are expected to be completed before the live projects start in July;\n\t but that doesn't mean you should give anything less than 1 hour a day or 7 hours a week towards the learning paths (LP).",
             21: "You can go back to that task and then click on 'More' and then 'resume' to restart that task.",
             22: "They are purposefully only configured for Desktops/ Laptops. In an emergency, you can use the 'show as desktop' mode of your browser.",
             23: "You can learn both the technologies using Learning Path 2 (LP2) which will begin after the 2nd week of March,\n\t but your internship will only be continuing with the one you are selected for.",
             24: "You cannot switch the technology currently. You have to continue with the one you are selected for.\n\t In the case of multiple form entries, you just got selected for one of them; the first one that you entered.\n\t You cannot make a switch right now.",
             25: "There is no metric to score your progress in any learning paths as it will be at a different pace for every individual.",
             26: "This could be because of some issue in the cookies or extension in your browser. Please try again with a different browser or open the tab with incognito mode.\n\t Also, you don't need to record your results, the quizzes are only for your knowledge check and not a metric to score you.",
             27: "Please ensure that you have connected to the drive of that workgroup by going to your notification and connecting to the drive of that workgroup.\n\t If that is done, please try to search for your workgroup in the search bar at the top of your screen.\n\t To search, use the keywords, 202003-IP-TechnologyName. Ex '202003-IP-DevOps'.\n\t In case there is no invitation to you, please message Cloud Counselage HR. You will be added to 2 groups “202003-IP” which is a general workgroup and the other one is “202003-IP-Technology” which is a technology-specific workgroup.",
             28: "Please follow the instructions given in the videos or the one in the Bitrix24 mail (these are the same videos share in the task), the tokens are given to you.\n\t Ensure that you are putting the right token on the right page.",
             29: "When does the LP1/ LP2/ LP3 begin dates and deadline/ end date?\n\t The dates to begin the learning paths (LP) are:\n\t LP1 - 01/03/2020\n\t LP2 - 18/03/2020\n\t LP3 - 02/04/2020\n\t All learning Paths (LP) are expected to be completed by the interns before the first week of June as Live Projects will begin in that time frame.",
             30: "The main focus of LP2 is to provide you with a basic foundation of the technology you're interested in.\n\t The training is also handpicked in such a way that they enable you to work on LP3 assignments which interim\n\t gives you the beginning to start your study for the selected technology and in no terms is the only final training you should look into.\n\t Please keep learning after your LP2 is complete, that is the only way to grow in your technology of choice.",
             31: "LP3 will be assignment based and its execution and content vary from technology to technology.\n\t This assignment will be like a mini-project for all interns in a particular technology which will be verified by Cloud Counselage Project Managers.",
             32: "You'll be given preparatory leave (PL) from April to June after that your Live Projects will be given after the first week of June.",
             33: "No, these pieces of training will cover basics and there is no harm in brushing up your skills before you start with the assignments later.",
             34: "If the tasks are completed, there is no need to clock-in and clock-out unnecessarily for hours.\n\t However, you should keep a track of all the updates of the internship being posted on the groups.",
             35: "Please do not skip any piece of training,\n\t in case you're not able to access any link please message to Cloud Counselage HR and drop an email to hrsupport@cloudcounselage.in regarding the same.",
             36: "We have provided our interns with preparatory leave from the exam season,\n\t nevertheless, you are free to work on your LP3 assignment, but we suggest to concentrate on your exams first.",
             37: "Yes, we'll provide every intern a joining letter as soon as all interns are inducted.",
             38: "Yes, you can do another internship outside of Cloud Counselage but please ensure to provide 1 hour a day or 7 hours a week for IP.",
             39: "Submit your project and once it's reviewed as successful, collect your internship letter. Your internship is complete after this. There is no stipend for live projects.\n\t If your work is sublime and we have a vacancy in the position you're interested in,\n\t you may be offered a chance for interviews and can get an offer letter from Cloud Counselage Pvt. Ltd.",
             40: "Joining letter to all the interns will be provided on or before the 31st of March 2020.",
             41: "This is a three (3) month internship conducted in the month of March, June & July 2020.\n\t You will receive your internship experience letter in August during the convocation only if you successfully submit your Live Project.",
             42: "Projects in LP3 and Live Projects will be relevant to your training and ongoing projects in Cloud Counselage.\n\t The actual problem statements will only be given when the LP3/ Live Project phase is in progress to keep the interns focused on LP1/ LP2.",
             43: "Please message ‘Cloud Counselage HR’ in Bitrix24",
             44: "All the LP3/ Live Projects are on an individual scale.",
             45: "In the menu select 'time and reports' ->worktime and then you could see your worktime or click on this link once you’re logged in to Bitrix24;\n\t https://cloudcounselage24.bitrix24.com/timeman/timeman.php",
             46: "LP1 training is common across all the technologies",
             47: "They are our training partners and we have handpicked this training to cover a certain topic for you.\n\t These training cover from the very basic to intermediate level and is the perfect medium for you to have a starting point.",
             48: "Yes, you could have\n\t but the reason to have these videos is to keep an enclosed environment for you to watch these tutorials without distractions with quizzes and forums for you to discuss in.\n\t As mentioned earlier, our main aim is to provide you with a starting point and baseline for the technology of your choice.",
             49: "Yes, Cloud Counselage has purposefully partnered with Edureka\n\t so as to enable our interns to get the advantage of the corporate benefits at 'no profit no loss' basis for Cloud Counselage, that we receive from the partnership.\n\t Being our interns, you can get huge discounts on the certifications you choose to enrol for through Cloud Counselage and Edureka.\n\t In case you want to know more about the discounts offered, please reach out to ‘Cloud Counselage HR’ or write to hrsupport@cloudcounselage.in.",
             50: "We have uploaded the videos of the highest quality and best resolution which has resulted in some videos being over 1 GB as they are of hours in duration.\n\t To experience these high definition videos we request you to wait at least 5 minutes or more; depending on your computer's RAM and internet connection.",
             51: "LP1/ LP2/ LP3 is your preparation for the Live Project. All the phases LP1/ LP2/ LP3/ Live Project are a part of this internship.",
             52: "The set of training is not exhaustive and you are required to keep learning about the technology on your own to excel in your Live Project.",
             53: "As mentioned in the video: -\n\t Step1: Go to lp1 module\n\t Step2: Select module\n\t Step3: Put token (it will direct you to the home screen if the token is correct)\n\t Step4: Again go to lp1 module n select that module\n\t Step5: You will get the access by now\n\t Step6: Register there (each time for every module)\n\t Step7: Give the quiz\n\t Step8: Logout",
             54: "If you have submitted the ‘New Joinee Form’ after the 1st of March, please wait till the 31st of March to receive your access.",
             55: "Yes, your friends can apply till the 30th of March 2020; https://www.cloudcounselage.com/ipmaharashtra/.\n\t To be a student representative of Cloud Counselage, please contact Cloud Counselage HR.",
             56: "As a precautionary measure to safeguard our intern’s health, we have decided to conduct all the inductions online.",
             57: "Our team will verify and then only your task shall be accepted as completed. Please wait till the verification's complete.",
             58: "Ensure that you have clicked ‘Start’ when you resume a task, the ‘Finish’ button gets active only after the task is started.\n\t Once you complete the task you can then click on ‘Finish’ and then the efficiency is updated in the system.\n\t However, please raise this issue with the Cloud Counselage HR, as they will look at it on a case to case basis.",
             59: "As this is an internship you’re expected to do self-learning, mentorship is not part of an internship.\n\t However, we have created forums to resolve your doubts in the form of workgroups.\n\t As an intern ensure that you are part of relevant workgroups, i.e. ‘202003 - IP’ and your resp. Technology workgroup.\n\t In case, you are not a part of these workgroups, please reach out to ‘Cloud Counselage HR’ on Bitrix24 Chat.",
             60: "Live Projects will be provided by Cloud Counselage as these are the ongoing projects of Cloud Counselage and your opportunity to create an impact in the organisation.",
             61: "All our current interns if performing well in our internship programs can be offered an opportunity to interview for various positions in Cloud Counsealge.\n\t Many of our now full-time employees were interns in Cloud Counselage.",
             62: "As this is an online internship you do not need to visit the offices in the duration of this internship.\n\t You will be requested to visit the Vikhroli office only once; i.e. on your internship convocation day which will be in July 2020.\n\t Nevertheless, you can visit our offices with an appointment.",
             63: "Yes, you can extend your internship by being part of our other online programs like, ‘Online Career Program’.",
             64: "You are not restricted from doing the training of other technologies but you will only be given an internship certificate of the technology you’re selected for.",
             65: "Live Projects will have only your part of technology even if there are multiple technologies that are a part of the project,\n\t you will be working only on the part that covers your technology.",
             66: "This could have an adverse effect on your internship, please contact Cloud Counsealge HR and provide a genuine reason to miss clock in/ clock out.\n\t Also, please start performing your clock in/ clock out now.",
             67: "You will receive LP3 and Live Projects of your respective technology.",
             68: "We do understand that you might be interested in other technologies and are eager to learn more,\n\t but we have prescribed the technologies based on your first inputs and cannot change your base technology.\n\t Nevertheless, you do have the opportunity to go through the training of all the technologies.",
             69: "The company policies will be published on www.cloudcounselage.co.in/ippolicies",
             70: "Once you submit your weekly report, your supervisor and the HR team shall take the cognizance.\n\t They would reach out to you in case of discrepancies, so you need not worry about the confirmation.",
             71: "It is showing the remaining time because it's configured for 8 working hours per day.\n\t Our interns need to only make sure that they are online for 1 hour per day or 7 hours a week.",
             72: "We have created a separate page with a pre-recorded induction,\n\t please visit it; https://www.cloudcounselage.co.in/ipinduction",
             73: "Yes. Although, you can always revisit the induction so that you can review what has been said in it.",
             74: "We have observed that there is such an attachment for a few mailing service providers like Gmail and yahoo, please ignore this attachment.\n\t It won’t cause any harm to your system.",
             75: "Please push you to code in a public repo of your GitHub account if required by your LP3 assignment.",
             76: "For now, please concentrate on completing the task. We will ask all the interns to submit their work in the first week of June.\n\t Ensure you make it up to the mark till then as there would be no extension given that time.",
             77: "We will review this task in May 2020.",
             78: "Live project's use case will strictly be provided by Cloud Counselage and you cannot choose your own use case.",
             79: "Yes, it is mandatory to do, we are trying to include some more tasks due to the current scenarios, but adherence to clock-in/ clock-out policy is utterly important.",
             80: "Yes, you can.",
             81: "As mentorship/ hand-holding is not part of an internship by definition, we would not provide any technical help.\n\t Nevertheless, feel free to ask your doubt in your respective workgroup chat/ in the community or Google it :)",
             82: "Please ask them to send a mail to hrsupport@cloudcounselage.in and wait till 30th April 2020 for a reply.",
             83: "As mentioned in the '202003-IP' workgroup, please ask all queries related to LP3 in your technology workgroup only and tag Jayanth G S in your message.",
             84: "If you had not attended the live induction and have registered in the pre-recorded session after 4 PM, 31st March.\n\t Then you'll get your joining letter by 30th April 2020.\n\t If you have otherwise, please a mail to hrsupport@cloudcounselage.in or ping 'Cloud Counselage HR' in B24.",
             85: "Since some of you are not able to download, please find the same document in your technology drive in the folder LP3.\n\t We have made an announcement in your respective technology workgroup as well, please check.",
             86: "Yes, you'll need to complete the mandatory training as cloud computing is fundamental to many technologies and this additional knowledge will help you in your career.",
             87: "This is due to many webpages opened, please close your browser and try again or you can open a new incognito tab and try again.",
             88: "Welcome",
             89: "Hi there! How can I help you?"
             }
# for file in files:
#     chats = open(file, 'r', encoding='utf-8').readlines()
#     trainer.train(chats)

# chats = open('intents.txt', 'r', encoding='utf-8').read()
# trainer.train(chats)
while True:
    request = input('You: ')
    if 'bye' in request:
        print('Bot: See you!')
        break
    else:
        response = 0
        flag = 0
        for key in keywords.keys():
            for k in keywords[key].keys():
                f = 0
                for word in keywords[key][k]:
                    if word in request:
                        f += 1
                if f == len(keywords[key][k]):
                    response = key
                    flag = 1
                    break
            if flag == 1:
                break
        print('Bot: {}'.format(responses[response]))
